chore(cmake): optimize install directory
linuxdeepin/dtkcommon pull request #45
Opened 2023-04-28 08:51 UTC by asterwyx

Use relative directory to support --prefix when install.

Log: optimize install directory

2023-04-28 09:05 UTC, wineee requested changes

2023-04-28 09:05 UTC, wineee commented on CMakeLists.txt
> +message(STATUS ${PROJECT_VERSION})
```suggestion
message(STATUS "PROJECT VERSION: ${PROJECT_VERSION}")
```

2023-04-28 09:05 UTC, zccrs requested changes

2023-04-28 09:05 UTC, zccrs commented on CMakeLists.txt
> +message(STATUS ${PROJECT_VERSION})
说明一下这里输出的是 Version？

2023-04-28 09:12 UTC, wineee commented on CMakeLists.txt
> +set (MKSPECS_INSTALL_DIR "${CMAKE_INSTALL_LIBDIR}/qt5/mkspecs" CACHE STRING "Install directory for qt pri files")
why dont use `CMAKE_INSTALL_FULL_LIBDIR`， `CMAKE_INSTALL_FULL_LIBDIR` also accept -DCMAKE_INSTALL_PREFIX=/XXX when CMAKE_INSTALL_LIBDIR is relative path

2023-05-04 01:28 UTC, asterwyx commented on CMakeLists.txt
> +set (MKSPECS_INSTALL_DIR "${CMAKE_INSTALL_LIBDIR}/qt5/mkspecs" CACHE STRING "Install directory for qt pri files")
to support `cmake --install build --prefix /tmp` etc.

2023-05-23 02:33 UTC, wineee approved these changes
libdtk-${PROJECT_VERSION} 改到 dtk${PROJECT_VERSION_MAJOR} 如果是 dtk 统一修改的话，没有问题

2023-05-23 02:36 UTC, asterwyx commented
> libdtk-${PROJECT_VERSION} 改到 dtk${PROJECT_VERSION_MAJOR} 如果是 dtk 统一修改的话，没有问题

这个很早之前其他组件就已经修改过了。

2023-05-30 06:43 UTC, zccrs approved these changes

2023-05-30 06:43 UTC, merged