refactor!: deprecate features and some workflows
linuxdeepin/dtkcommon pull request #47
Opened 2023-07-11 09:53 UTC by asterwyx

- refactor!: remove Qt features for DTK
- chore: remove deprecated workflow

2023-07-12 01:40 UTC, kegechen approved these changes

2023-07-12 01:41 UTC, kegechen commented
@BLumia 这个 workflow 是不是可以删了。

2023-07-12 02:01 UTC, BLumia commented on .github/workflows/call-build-distribution.yml
提个 PR 把https://github.com/linuxdeepin/.github/blob/10163e69ff1a94529ac1d0ae8f083cbc6b0e3eeb/repos/linuxdeepin/dtkcommon.json#L33-L39 删了吧

2023-07-12 03:13 UTC, kegechen approved these changes

2023-07-12 03:16 UTC, asterwyx commented
/check obs

2023-07-12 07:11 UTC, 18202781743 requested changes
333

2023-07-21 06:48 UTC, asterwyx commented
/check obs

2023-07-21 08:11 UTC, 18202781743 approved these changes

2023-07-21 08:15 UTC, asterwyx commented
/merge

2023-07-21 08:15 UTC, merged